kba_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CH_HOST', 'localhost') }}"
      port: 9000
      user: default
      password: ""
      schema: silver